#!/usr/bin/env python3

import sys
import subprocess
from subprocess import CalledProcessError, Popen, PIPE, check_call
import textwrap

from dialogs import (dialog_input, get_key_size, get_country_code,
    error_and_exit, msgbox)


def generate_rsa_key(domain, keysize, filename):
    cmd = [
        "openssl", "genrsa", "-out", filename, keysize
    ]
    try:
        check_call(cmd)
    except CalledProcessError as cpe:
        error_and_exit("Failure generating RSA key!")


def extract_public_key(filename):
    outname = filename.rsplit('.', 1)[0] + ".pubkey"
    cmd = [
        "openssl", "rsa", "-in", filename, "-pubout", "-out", outname
    ]
    try:
        check_call(cmd)
    except CalledProcessError as cpe:
        error_and_exit("Failure extracting public key from {}!".format(
            filename))
    return outname


def main():
    domain_name = dialog_input("Domain Name")
    key_size = get_key_size()
    filename = dialog_input("Key Output Filename", initial=domain_name+".key")

    generate_rsa_key(domain_name, key_size, filename)
    pubkey_filename = extract_public_key(filename)

    msgbox("Public key extracted to: {}".format(pubkey_filename))


if __name__ == '__main__':
    main()
